# Generated by Django 4.1.1 on 2022-10-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0002_alter_auction_description_delete_profile"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="favorites",
            field=models.ManyToManyField(to="auction.auction"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="account_type",
            field=models.BooleanField(default=False),
        ),
    ]
