# Generated by Django 4.1.1 on 2022-10-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="description",
            field=models.TextField(max_length=2047),
        ),
        migrations.DeleteModel(name="Profile",),
    ]
