# Generated by Django 4.1.1 on 2022-10-17 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auction", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating", old_name="comment_buyer", new_name="comment",
        ),
        migrations.RenameField(
            model_name="rating", old_name="rating_buyer", new_name="rating",
        ),
        migrations.RemoveField(model_name="rating", name="comment_seller",),
        migrations.RemoveField(model_name="rating", name="rating_seller",),
        migrations.AddField(
            model_name="rating",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
