# Generated by Django 4.1.1 on 2022-10-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0002_rename_comment_buyer_rating_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="min_amount",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
