# Generated by Django 4.1.1 on 2022-10-19 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0005_auction_fin"),
    ]

    operations = [
        migrations.RemoveField(model_name="auction", name="fin",),
    ]
